name: Task
on:
  push:
  
jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
       - name: HelloWorld
         run: |
           docker run HelloWorld
           mkdir artifacts 
           cd artifacts
           wget https://hub.docker.com/_/hello-world
       - uses: actions/upload-artifact@v2

