name: Docker_Task
on:
  push:
  
jobs:
  Docker:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v3
        - name: fix docker 
          shell: bash
          run: sudo chmod 666 /var/run/docker.sock

        - name: docker build
          shell: bash
          run: docker build -t builder .

        - name: docker run
          shell: bash
          run: |
            docker run --name=taskdock -v "$(pwd)/logs/:/home/logs/" builder
            exit
            

        - name: docker cp
          shell: bash
          run: docker cp taskdock:/task/_build artifacts
            
            

        - name: artifacts
          shell: bash
          run: |
            mkdir artifacts
            touch touch artifacts/artifacts.txt
            docker inspect builder > artifacts/artifacts.txt
            
        - name: Publish
          uses: actions/upload-artifact@v2
          with:
            name: artifacts
            path: artifacts/

